name: flutter_weather
description: A Flutter application to view current weather status.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  equatable: ^1.2.6
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  intl: ">=0.16.1"
  shared_preferences: 0.5.12+4
  geolocator: ^6.2.1
  permission_handler: ^5.1.0+2
  # charts_flutter: ^0.10.0
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  flutter_swiper : ^1.1.6
  #flutter_native_splash: ^0.3.2
  flutter_native_splash: ">=0.3.2"
  easy_localization: ">=2.3.3+1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  #flutter_test:
  #  sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf

  assets:
    - assets/translations/